c("affiliation_namer" ,"c"
, "character2name" ,"correspondings"
, "d_author_affiliations" ,"d_j1"
, "d_j2" ,"d_j3"
, "df3" ,"df4"
, "df5" ,"display_abstract"
, "display_affiliations" ,"display_author_affiliations"
, "display_author_note" ,"display_authors"
, "display_corresponding_author" ,"display_keywords"
, "display_orcids" ,"display_title"
, "display_title_heading" ,"f_abstract_display"
, "f_affiliations_display" ,"f_author_affiliations"
, "f_author_affiliations_display" ,"f_author_display"
, "f_author_note_blanks" ,"f_author_note_display"
, "f_author_note_second_paragraph" ,"f_author_note_third_paragraph"
, "f_author_roles" ,"f_corresponding_author_display"
, "f_correspondings" ,"f_keywords_display"
, "f_orcids_display" ,"f_title_blanks"
, "f_title_display" ,"f_title_heading_display"
, "get_metadata" ,"has_annotations"
, "is_docx" ,"is_empty"
, "is_pdf" ,"large"
, "med" ,"one"
, "pw" ,"small"
, "t_j1" ,"t_j2"
, "t_j3" ,"w"
, "yml_metadata")

setdiff(
c("affiliation_namer" ,"c"
, "character2name" ,"correspondings"
, "d_author_affiliations" ,"d_j1"
, "d_j2" ,"d_j3"
, "df3" ,"df4"
, "df5" ,"display_abstract"
, "display_affiliations" ,"display_author_affiliations"
, "display_author_note" ,"display_authors"
, "display_corresponding_author" ,"display_keywords"
, "display_orcids" ,"display_title"
, "display_title_heading" ,"f_abstract_display"
, "f_affiliations_display" ,"f_author_affiliations"
, "f_author_affiliations_display" ,"f_author_display"
, "f_author_note_blanks" ,"f_author_note_display"
, "f_author_note_second_paragraph" ,"f_author_note_third_paragraph"
, "f_author_roles" ,"f_corresponding_author_display"
, "f_correspondings" ,"f_keywords_display"
, "f_orcids_display" ,"f_title_blanks"
, "f_title_display" ,"f_title_heading_display"
, "get_metadata" ,"has_annotations"
, "is_docx" ,"is_empty"
, "is_pdf" ,"large"
, "med" ,"one"
, "pw" ,"small"
, "t_j1" ,"t_j2"
, "t_j3" ,"w"
, "yml_metadata"),
c("affiliation_namer" 
  , "character2name" ,"correspondings"
  , "d_author_affiliations","display_abstract"
  , "display_affiliations" ,"display_author_affiliations"
  , "display_author_note" ,"display_authors"
  , "display_corresponding_author" ,"display_keywords"
  , "display_orcids" ,"display_title"
  , "display_title_heading" ,"f_abstract_display"
  , "f_affiliations_display" ,"f_author_affiliations"
  , "f_author_affiliations_display" ,"f_author_display"
  , "f_author_note_blanks" ,"f_author_note_display"
  , "f_author_note_second_paragraph" ,"f_author_note_third_paragraph"
  , "f_author_roles" ,"f_corresponding_author_display"
  , "f_correspondings" ,"f_keywords_display"
  , "f_orcids_display" ,"f_title_blanks"
  , "f_title_display" ,"f_title_heading_display"
  , "get_metadata" ,"has_annotations"
  , "is_docx" ,"is_empty"
  , "is_pdf" 
  , "yml_metadata"))
