---
title: "Sample and Simulated Data"
author: "Cillian McHugh"
date: "`r format(Sys.time(), '%d %B, %Y')`"
keywords          : "moral dumbfounding, dual-processes, reasons, intuitions"
bibliography: "resources/bib/My Library.bib"
figsintext        : yes
figurelist        : yes
tablelist         : yes
footnotelist      : no
lineno            : yes
lang              : "english"
class             : "man"
format:
  html:
    toc: true
    toc-depth: 4
    toc-location: left
editor_options: 
  chunk_output_type: console
---


```{r ch5setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(include = FALSE)
options(scipen=1, digits=2)
# knitr::opts_chunk$set(fig.path='figure/graphics-', 
#                       cache.path='cache/graphics-', 
#                       fig.align='center',
#                       external=TRUE,
#                       echo=FALSE,
#                       warning=FALSE,
#                       fig.pos='H'
# )
```


```{r}
rm(list=ls())
library(conflicted)
library(tidyverse)
library(mlogit)
library(DescTools)
library(nnet)
library(pwr)
#library(reshape2)
#conflicts_prefer(dplyr::filter, .quiet = TRUE)

```

```{r}
# df <- read_csv("sample_data/sample_data.csv")
# 
# head(df)
# variable.names(df)
# 
# df <- df[-c(1:2),]

source("simulate_data.R")

df3 <- simulated_data

```

```{r}
x <- simulated_data
table(x$condition6)
table(x$psych,x$temp)

```


```{r}
#| include: false

# 
# x <- rbind(simulated_data,simulated_data)
# 
# lme4::lmer(cs ~ 
#               psych
#             + temp
#             + (1|ResponseId)
#            , data = x
#            #, family = gaussian
#            )
# 
# help(lmer)
# x$ResponseId
# 
# nlme::lme(cs ~ 
#             ju1_2
#             #   psych
#             # + temp
#     ,
#           data = x, random = ~ 1 | ResponseId)
# 
# 
# 
# model0 <- lmerTest::lmer(cs ~ 1
#                 #   condition
#                  + (1|ResponseId)
#                 # + (1|ResponseId:condition)
#                 , data = x
#           #      , contrasts = list(condition = contr.sum  , valence = contr.sum)
#             )
# 
# 
# 
# summary(model0)
# model1 <- lmerTest::lmer(ju1_2 ~
#                   condition5#*scenario
#                  + (1|ResponseId)
#                 # + (1|ResponseId:condition)
#                 , data = x
#                 #, contrasts = list(condition = contr.sum  )#, valence = contr.sum)
#             )
# summary(model1)
# anova(model1)


```



```{r}
#| label: dlogit1
#| include: false

#df3$cs <- relevel(df3$cs, ref = 2)

df3a <- mlogit.data(df3, choice = "cs", shape = "wide")
InCSModel<-mlogit(cs ~ 1 | psych+temp, data = df3a)# , reflevel = 2)

InCSModel


summary_InCS_model <- summary(InCSModel)
summary_InCS_model

summary_InCS_model$lratio$parameter
summary_InCS_model$lratio$statistic
summary_InCS_model$lratio$p.value

InCSModel$coefficients[3]
InCSModel$coefficients[4]

cox <- DescTools::PseudoR2(multinom(cs~psych,df3), "all")

cox[3]
cox[4]
#PseudoR2(x, "all")
#summary_InCS_model


wald1 <- 
  summary_InCS_model$CoefTable[3]^2 /
  summary_InCS_model$CoefTable[7]^2

wald2 <- 
  summary_InCS_model$CoefTable[4]^2 /
  summary_InCS_model$CoefTable[8]^2


summary_InCS_model
summary_InCS_model$coefficients[3]
data.frame(exp(InCSModel$coefficients))

exp(InCSModel$coefficients)[3]


a <- exp(confint(InCSModel))
c(a[3],a[7])

residuals(InCSModel)
fitted(InCSModel, outcome = F)

c <- summary_InCS_model$lratio$statistic
w <- sqrt(c/length(df3$gender))
pw <- pwr.chisq.test(w=w,N=length(df3$cs),df=(2),sig.level = .05)

pw$power

revised_PseudoR2s <- function(LogModel) {
  dev <- LogModel$deviance
  nullDev <- LogModel$null.deviance
  modelN <- length(LogModel$fitted.values)
  R.l <- 1 - dev / nullDev
  R.cs <- 1- exp ( -(nullDev - dev) / modelN)
  R.n <- R.cs / ( 1 - ( exp (-(nullDev / modelN))))
  
  all <- list(hosmer_and_lemeshow = as.numeric(R.l), mcfadden = NA, cox_and_snell = as.numeric(R.cs), nagelkerke = as.numeric(R.n))
  all
}

logits_rsquared <- glm(cs~psych*temp*scenario,x, family = binomial(link = "logit"))
cox <- revised_PseudoR2s(logits_rsquared)
cox
summary(logits_rsquared)

logits_rsquared


glm1 <- glm(cs~psych+temp,x, family = binomial(link = "logit"))
glm0 <- update(glm1, . ~ 1)
anova(glm0,glm1,test="Chisq")

# https://stats.stackexchange.com/questions/69664/comparing-nested-glms-via-chi-squared-and-loglikelihood#69777


```

### Distancing and Dumbfounding

There was a significant association between experimental condition and response to the critical slide $\chi$^2^(`r summary_InCS_model$lratio$parameter`, *N* = `r length(df3$cs)`) = `r round(summary_InCS_model$lratio$statistic, digits=2)`, *p* `r paste(p_report(summary_InCS_model$lratio$p.value))`, The observed power was `r round(pw$power,digits=2)`. 

